---
apiVersion: v1
kind: Namespace
metadata:
  name: rhobs-testing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: token-refresher
  name: token-refresher
  namespace: rhobs-testing
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: token-refresher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: token-refresher
    spec:
      containers:
      - args:
        - --log.level=debug
        - --log.format=logfmt
        - --web.listen=0.0.0.0:8080
        - --web.internal.listen=0.0.0.0:8081
        - --oidc.audience=$(OIDC_AUDIENCE)
        - --oidc.client-id=$(OIDC_CLIENT_ID)
        - --oidc.client-secret=$(OIDC_CLIENT_SECRET)
        - --oidc.issuer-url=$(OIDC_ISSUER_URL)
        - --url=$(OBSERVATORIUM_API_URL)
        env:
        - name: OIDC_AUDIENCE
          valueFrom:
            secretKeyRef:
              key: audience
              name: token-refresher-oidc
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: clientID
              name: token-refresher-oidc
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: clientSecret
              name: token-refresher-oidc
        - name: OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              key: issuerURL
              name: token-refresher-oidc
        - name: OBSERVATORIUM_API_URL
          valueFrom:
            secretKeyRef:
              key: apiURL
              name: token-refresher-oidc
        image: quay.io/observatorium/token-refresher:master-2022-03-20-731cadd
        name: token-refresher
        ports:
        - containerPort: 8081
          name: internal
        - containerPort: 8080
          name: web
